@startuml ssd-uc2-4

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

participant "PC" as pc
actor Admin as admin

actor Users as users
participant "Server" as server
collections "ComUnit : UserKit" as comUnit
collections "transmitter : UserKit" as transmitter
collections "reciever : UserKit" as reciever
participant "Laser-Tag 3000" as laserTag
participant "Ramt lasermodtager" as laserReciever

== Use case 2: Start spil ==

group Prækondition
    users -> admin: To eller flere brugere henvender sig
end

activate admin
admin -> pc: Vælger at starte spil
activate pc
admin -> pc: Indtaster længden på spillet
admin -> pc: Indtaster antal spillere
admin -> pc: Bekræfter indtastningerne
admin -> pc: Bekræfter start af spil
deactivate admin
pc -> server: Start spil
deactivate pc
activate server
server -> comUnit: Spil startet
deactivate server

== Use case 3: Skyd ==

group Prækondition
    users -> transmitter: En bruger trykker på aftrækkeren
    activate transmitter
    transmitter -> reciever: Udsender laserstråle
    deactivate transmitter
    activate reciever
    reciever -> reciever: Modtager ramt
end

reciever -> comUnit: Fortæller hvilken bruger, der har ramt modtageren
deactivate reciever

comUnit -> server: Sender information om ramt modtager til server

'Her går der noget galt - det er vel modtageren der detektere det og sender til server???
laserTag -> laserTag: Detektere at brugeren rammer en lasermodtager
laserTag -> server: Hældelsen logges i servern
'Hvordan ved brugeren hvor mange point han har???
laserReciever -> laserReciever: Vibrerer og blinker

== Use case 4: Afslut spil ==

server -> server: Statistikker for det afsluttede spil opdateres
server -> laserTag: Point og statistikker downloades
laserTag -> laserTag: Point og statistikker vises på en skærm

@enduml