@startuml ssd-uc2-4

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

actor Admin as admin
participant "GUI" as gui
participant "Laser-Tag 3000" as lasertag
participant "Database" as database
participant "Ramt lasermodtager" as laserReciever

== Use case 2: Start spil ==

admin -> gui: Vælger at starte spil
admin -> gui: Indtaster længden på spillet
admin -> gui: Bekræfter indtastningerne
admin -> gui: Indtaster antal spillere

'Mangler: Spil startes (Men hvordan??? Fra GUI til server til enheder???)

== Use case 3: Skyd ==

'Her går der noget galt - det er vel modtageren der detektere det og sender til database???
lasertag -> lasertag: Detektere at brugeren rammer en lasermodtager
lasertag -> database: Hældelsen logges i databasen
'Hvordan ved brugeren hvor mange point han har???
laserReciever -> laserReciever: Vibrerer og blinker

== Use case 4: Afslut spil ==

database -> database: Statistikker for det afsluttede spil opdateres
database -> lasertag: Point og statistikker downloades
lasertag -> lasertag: Point og statistikker vises på en skærm

@enduml