@startuml ssd-uc1

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

actor Bruger as user
participant "Target" as tgt
participant "Server" as svr

'== Use case 1 ==

user -> tgt: Tænder for
activate tgt
loop 5 sekunder
    tgt -> tgt: Nulstil position
end
tgt -> tgt: Start bevægelse

loop 60 sekunder
    tgt -> tgt: Bevæger sig i tilfældig sekvens
    user -> tgt: Skyder efter target

    alt target rammes
        tgt <- tgt: Target ramt: Point +1
    end
end

tgt -> tgt: Stop bevægelse

tgt -> svr: Point sendes til server
deactivate tgt
activate svr
svr -> user: Point vises til bruger
deactivate svr

@enduml