@startuml uc_diagram

left to right direction

skinparam {
  monochrome true
  dpi 300
  padding 5
  packageStyle rectangle
  packageStyle frame
  shadowing false
  'linetype polyline
  'linetype ortho
  'backgroundColor transparent
}

frame "uc Laser-Tag 3000" {

  actor Bruger as user
  actor Administrator as admin

  rectangle "Laser-Tag 3000" {
    user -- (UC1: Øve på target)
    user -- (UC2: Start spil): 2..10
    user -- (UC3: Skyd): 1..2
    admin -- (UC2: Start spil)
    admin -- (UC4: Afslut spil)
  }
}

@enduml