@startuml deployment_diagram

skinparam {
    monochrome true
    dpi 300
    padding 5
    packageStyle rectangle
    packageStyle frame
    shadowing false
}

frame "Deployment diagram" {

node "<b>PC" <<device>> as PC {
    node "<b>Desktop App" <<application>> as desktopApp {
        artifact "<b>frontend.exe" <<executable>> as frontend
    }
    note "This application serves\n as the admin interface" as N2
    N2 .. desktopApp

    node "<b>Server" <<server>> as server {
        artifact "<b>backend.exe" <<executable>> as backend
    }

    database "<b>High score database\n----" <<database>> as DB {
        entity "HighScore"
        entity "Users"
    }
}

together {
    node "<b>UserKit" <<device>> as UserKit {
        node "<b>UserKitController" <<device>> as userKitCtrl {
            artifact "userkitApp" <<executable>>
        }

        node "<b>UserKit Communication Unit" <<device>> as UsrComUnit {
            artifact "comApp" <<executable>> as usrComApp
        }
    }

    node "<b>PracticeKit" <<device>> as PracticeKit {
        node "<b>PracticeKitController" <<device>> as PracticeKitCtrl {
            artifact "practiceKitApp" <<executable>>
        }

        node "<b>PracticeKit Communication Unit" <<device>> as TrgtComUnit {
            artifact "comApp" <<executable>> as trgtComApp
        }
    }

    node "<b>TargetController" <<device>> as TargetKit {
        artifact "regulatorApp" <<executable>> as targetApp
    }

    node "<b>Scoreboard Display" <<device>> as scoreboard {
        note "Access a HTTP server from a browser" as N1
    }
}

' PC -- UserKit
' PC -- PracticeKit
' PC -- scoreboard


UserKit -- PC : <<protocol>>\nWebSocket
PracticeKit -- PC : <<protocol>>\nWebSocket
scoreboard -- PC : <<protocol>>\nHTTP

server - DB
desktopApp - server : <<protocol>>\nWebSocket

}

@enduml