@startuml frontend_class_diagram

skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

    class Players {
        + addPlayer(): void
        + removePlayer(): void
    }

    class Player {
        - score: int
        - name: string
    }

    class MainWindow {
        + quitApplication(): void
        + openMenu(): void
    }

    class ServerAPI <<boundary>> {
        +addPlayer(): string
        +removePlayer(): string
        +startGame(): string
        +clearHighscore(): string
    }

    MainWindow *-- "1" ServerAPI
    MainWindow *-- "1" Players
    Players o-- "1..*" Player

@enduml