@startuml practiceKitCtrlApp_cd

skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

frame "cd userKitCtrlApp" {

    class main <<utility>> {
        currentLaserID : int
    }

    class PracticeKitCtrl <<controller>> {
        init() : void
    }

    class PracticeKitComUnitIF <<boundary>> {
        receiverHit(currentLaserID : int) : void
    }

    class Receiver <<controller>> {
        changeMixerFrequency(currentLaserID : int) : int
    }
}

main -- PracticeKitCtrl
main -- Receiver
main -- PracticeKitComUnitIF

@enduml