@startuml practiceKitCtrlApp_cd

skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

frame "cd userKitCtrlApp" {

    class main <<utility>> {
    }

    class PracticeKitCtrl <<controller>> {
        initPracticeKitCtrl() : void
    }

    class ComUnitIF <<boundary>> {
        initComUnitIF(void) : void
        sendHitInd(currentLaserID : int) : void
        sendPracticeKitStartInd(void) : void
    }

    class Receiver <<controller>> {
        receiverHit(void) : void
        changeMixerFrequency(currentLaserID : int) : int
    }
}

main -- PracticeKitCtrl
main -- Receiver
main -- ComUnitIF

@enduml