@startuml practiceKitCtrlApp_sd

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

mainframe **sd** praticeKitCtrlApp

participant main <<utility>>
participant PraticeKitCtrl <<controller>>
participant PracticeKitComUnitIF <<boundary>>
participant Receiver <<controller>>

main -> PraticeKitCtrl: init(unitID : int)

loop
    activate main
    main -> Receiver++: checkReceiver()
    return currentLaserID or 0 on faliure

    alt succes
        main -> main: disable all interrupts
        main -> PracticeKitComUnitIF++: receiverHit(currentLaserID)
        return succes/faliure
        main -> main: sleep (blocking)
        main -> main: enable all interrupts
        deactivate main
    end

    else Interrupt from mixerFrequencyTimer
    [o-> main: <<mixerFrequencyTimer event>>
    activate main
    main -> Receiver++: changeMixerFrequency()
    deactivate main
    deactivate Receiver
end


@enduml