@startuml practiceKitCtrlApp_sd

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

mainframe **sd** praticeKitCtrlApp

participant main <<utility>>
participant PraticeKitCtrl <<controller>>
participant ComUnitIF <<boundary>>
participant Receiver <<controller>>

main -> PraticeKitCtrl++: initPracticeKitCtrl()
deactivate PraticeKitCtrl
main -> ComUnitIF++: initComUnitIF()
deactivate ComUnitIF

loop
    rnote over main, Receiver : Empty loop

    else Interrupt from isr_filter
    [o-> main: <<filter event>>
    activate main

    main -> main: Update filterOutputVolt

    alt filterOutputVolt > minLevelDetection || filterOutputVolt > -minLevelDetection
        main -> Receiver++: receiverHit()
        main -> ComUnitIF++: sendHitInd(currentLaserID)
        deactivate main
        deactivate Receiver
        deactivate ComUnitIF
    end

    else Interrupt from isr_mixerFreq
    [o-> main: <<mixerFreq event>>
    activate main
    main -> Receiver++: changeMixerFrequency(currentLaserID)
    return newLaserID
    deactivate main

    else Interrupt from isr_practiceKitStart
    [o-> main: <<practiceKitStart event>>
    activate main
    main -> ComUnitIF++: sendPracticeKitStartInd()
    deactivate main
    deactivate ComUnitIF
end

@enduml