@startuml practiceKitCtrlApp_cd

skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

frame "cd userKitCtrlApp" {

    class main <<utility>> {
        unitID : char
        laserID : char
    }

    class PracticeKitCtrl <<controller>> {
        init(unitID : char) : void
    }

    class PracticeKitComUnitIF <<boundary>> {
        receiverHit(currentLaserID : char) : bool
    }

    class Receiver <<controller>> {
        checkReceiver() : char
    }
}

main -- PracticeKitCtrl
main -- Receiver
main -- PracticeKitComUnitIF

@enduml