@startuml ssd-uc2-4

hide footbox

skinparam {
    monochrome true
    dpi 200
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

mainframe **sd** Use case 2-4

actor Users as users
actor Admin as admin
participant "PC" as pc
collections "ComUnit : UserKit" as comUnit
collections "transmitter : UserKit" as transmitter
collections "reciever : UserKit" as reciever
participant "Server" as server
participant "ScoreDisplay" as display

== Use case 2: Start spil ==

group Prækondition
    users -> admin: To eller flere brugere henvender sig
end

activate admin
admin -> pc: Vælger at starte spil
activate pc
admin -> pc: Indtaster længden på spillet
admin -> pc: Indtaster antal spillere
admin -> pc: Bekræfter indtastningerne
admin -> pc: Bekræfter start af spil
deactivate admin
pc -> server: Start spil samt informationer om spil
deactivate pc
activate server
server -> comUnit: Spil startet
deactivate server
activate comUnit
comUnit -> comUnit: Starter timer

== Use case 3: Skyd ==

group Prækondition
    users -> transmitter: En bruger trykker på aftrækkeren
    activate transmitter
    transmitter -> reciever: Udsender laserstråle
    deactivate transmitter
    activate reciever
    reciever -> reciever: Modtager ramt: Vibrerer og blinker
end

reciever -> comUnit: Fortæller hvilken bruger, der har ramt modtageren
deactivate reciever

comUnit -> server: Sender information om ramt modtager til server

== Use case 4: Afslut spil ==

alt Timer udløber
    comUnit -> server: Spil afsluttes
else Admin afbryder spil
    admin -> server: Afslut spil
    server -> comUnit: Afbryd spil

end

server -> server: Statistikker for det afsluttede spil opdateres
server -> display: Point og statistikker vises på skærm

@enduml