@startuml ssd-uc1

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

mainframe **sd** Use case 1

actor Bruger as user

participant "UserKit" as userKit
participant "PracticeKit" as practiceKit
participant "Target" as target
participant "PC" as pc

'== Use case 1 ==
user -> practiceKit++: Trykker på knap på PracticeKit
practiceKit -> pc++: Practice selected

pc -> pc: Starter nedtælling på 5 sekunder
practiceKit -> target++: Nulstiller position
deactivate target

loop 5 sekunder
    pc -> pc: Netælling vises på GUI
end

pc -> pc: Starter nedtælling på 60 sekunder
practiceKit -> target: Start bevægelse
activate target

loop 60 sekunder
    pc -> pc: Netælling vises på GUI

    target -> target: Bevæger sig i tilfældig sekvens
    user -> userKit: Skyder efter target

    alt Target rammes
        practiceKit -> pc: Point sendes til server
        pc -> pc: Point vises på ScoreDisplay
    end
end

practiceKit -> target: Stop bevægelse
deactivate target
deactivate practiceKit

user -> pc: Samlet antal point aflæses på ScoreDisplay
deactivate pc

@enduml