@startuml ssd-uc2-4

hide footbox

skinparam {
    monochrome true
    dpi 200
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

mainframe **sd** Use case 2-4

actor Users as users
actor Admin as admin
participant "PC"
collections "UserKitComUnit" as comUnit
participant "UserKitCtrl (User 1)" as kitCtrl1
participant "UserKitCtrl (User 2)" as kitCtrl2
participant "ScoreDisplay" as display

== Use case 2: Start spil ==

group Prækondition
    users -> admin: To eller flere brugere henvender sig
    activate admin
end

admin -> PC: Vælger at starte spil
activate PC
admin -> PC: Indtaster længden på spillet
admin -> PC: Indtaster antal spillere
admin -> PC: Bekræfter indtastningerne
admin -> PC: Bekræfter start af spil
deactivate admin
PC -> PC: Starter timer
PC -> comUnit: Spil startet
activate comUnit

== Use case 3: Skyd ==

group Prækondition
    users -> kitCtrl1: En bruger trykker på aftrækkeren
    activate kitCtrl1
    kitCtrl1 -> kitCtrl2: Udsender laserstråle
    deactivate kitCtrl1
    activate kitCtrl2
end

kitCtrl2 -> kitCtrl2: Modtager ramt: Vibrerer og blinker
kitCtrl2 -> comUnit: Fortæller hvilken bruger, der har ramt modtageren
deactivate kitCtrl2
comUnit -> PC: Sender information om ramt modtager til PC


== Use case 4: Afslut spil ==

alt Timer udløber
    admin -> PC: Afslut spil
else Admin afbryder spil
    admin -> PC: Spil afbrudt
end

PC -> comUnit: Afslut spil
deactivate comUnit

PC -> PC: Statistikker for det afsluttede spil opdateres
PC -> display: Point og statistikker gøres tilgængelige på skærm
deactivate PC

@enduml