' WORK IN PROGRESS
@startuml practiceKitCtrlApp_cd
scale 1.5
skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

frame "cd targetCtrlApp" {

    class main <<utility>> {
        initMain(void): void
    }

    class MotorControl <<controller>> {
        setPoint : uint16_t
        motorControlInit(void) : void
        motorChangeSetPoint(uint16_t newSetPoint) : void
        getPositionControl(uint16_t distance): int
    }

    class SonarDriver <<controller>> {
        sonarStart(void) : void
        sonarGetPosition(uint16_t sampleTimeUs) : int
    }
}

main -- MotorControl
main -- SonarDriver

@enduml