@startuml targetCtrlApp_sd

hide footbox

skinparam {
    monochrome true
    dpi 300
    padding 5
    sequenceMessageAlign center
    packageStyle frame
    shadowing false
    'backgroundColor transparent
}

mainframe **sd** targetCtrlApp

participant main <<utility>>
participant MotorControl <<controller>>
participant SonarDriver <<controller>>


activate main
main -> main: initMain()
main -> MotorControl: motorControlInit()
activate MotorControl
deactivate MotorControl
main -> SonarDriver: SonarInit()
activate SonarDriver
deactivate SonarDriver
deactivate main

loop Practice
/'
    else Reset position
    activate main
    loop
        main -> SonarDriver: sonarGetPosition(uint16_t sampleTimeUs)
        activate SonarDriver
        return distance
        deactivate SonarDriver
        main -> MotorControl: get position control(zero position)
        activate MotorControl
        return positionCtrl
        deactivate MotorControl
        main -> main: Move to position
        main -> main: Sample delay
        MotorControl -[hidden]> main
        deactivate MotorControl
        deactivate main
    end
'/

    [o-> main: <<start practice>>
    activate main
    main -> MotorControl: writeKillMotor(false)
    activate MotorControl
    deactivate MotorControl
    main -> MotorControl: motorChangeSetPoint(startPosition)
    loop Practice for 60 seconds
        alt Five seconds passed
            main -> main: generateNewSetPoint()
            main -> MotorControl: motorChangeSetPoint()
            main -> main: Start timeout interrupt counter
            main -> main: Start practice timer (60 sec)
        end
        main -> SonarDriver: sonarGetPosition(uint16_t sampleTimeUs)
        activate SonarDriver
        return distance
        deactivate SonarDriver
        main -> MotorControl: getPositionControl(distance)
        activate MotorControl
        MotorControl -> MotorControl: Move to position
        MotorControl -[hidden]> main
        deactivate MotorControl
        main -> main: Sample delay

        alt 
            [o-> main: <<TimeOut interrupt>>
            main -> main: generateNewSetPoint
            main -> MotorControl: motorChangeSetPoint(NewSetPoint)

        end
    end
    'MotorControl -[hidden]> main
    main -> MotorControl: writeKillMotor(true)
    activate MotorControl
    deactivate MotorControl
    deactivate main
end

@enduml