@startuml userKitCtrlApp_cd

skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

frame "cd userKitCtrlApp" {

    class main <<utility>> {
        unitID : int
        laserID : int
    }

    class UserKitCtrl <<controller>> {
        init(unitID : int) : void
    }

    class UserKitComUnitIF <<boundary>> {
        receiverHit(currentLaserID : int) : bool
    }

    class Transmitter <<controller>> {
        startTransmitting(void) : void
        stopTransmitting(void) : void
    }

    class Receiver <<controller>> {
        checkReceiver() : int
    }
}

main -- UserKitCtrl
main -- Transmitter
main -- Receiver
main -- UserKitComUnitIF

@enduml