@startuml UserKitCtrlApp_cd

skinparam {
    monochrome true
    dpi 300
    padding 2
    packageStyle rectangle
    packageStyle frame
    shadowing false
    classAttributeIconSize 0
}
hide circle
hide empty members

frame "cd userKitCtrlApp" {

    class main <<utility>> {
        unitID : char
        laserID : char
    }

    class UserKitCtrl <<controller>> {
        init(unitID : char) : void
    }

    class UserKitComUnitIF <<boundary>> {
        recieverHit(currentLaserID : char) : bool
    }

    class Transmitter <<controller>> {
        startTransmitting(void) : void
        stopTransmitting(void) : void
    }

    class Receiver <<controller>> {
        checkReceiver() : char
    }
}

main -- UserKitCtrl
main -- Transmitter
main -- Receiver
main -- UserKitComUnitIF

@enduml